
# Information needs {#information}

## European level

Every six years each EU member state needs to report on the conservation status of the European protected habitat types listed in Annex 1 of the Habitat Directive.

The conservation status of habitat types should be assessed per biogeographical region and is determined by four criteria [@dgenvironment2017]:

-   **Range**
-   **Area**
-   **Specific structure and functions (including typical species)**
-   **Future prospects**

Each of these criteria is evaluated according to the evaluation matrix specified in the reporting guidelines in @dgenvironment2017.

The conservation status of **specific structure and functions (including typical species)** is assessed as follows:

-   **Favourable**: structures and functions (including typical species) in good condition and no significant deteriorations / pressures
-   **Unfavourable - Bad**: more than 25% of the area is unfavourable as regards its specific structures and functions (including typical species)
-   **Unfavourable -- Inadequate**: any other combination
-   **Unknown**: no or insufficient reliable information available

The guidelines [@dgenvironment2017] stress the importance of trend information, as trends are decisive for the assessment of conservation status since usually only stable or positive trends can result in an overall favourable conservation status (FCS) conclusion. It is advised that more attention should be paid to the methodology of monitoring schemes to improve the quality of trend information. A short-term trend is considered as the trend over two reporting cycles (12 years). The recommended period for assessing longer-term trends is four reporting cycles (24 years).

## Regional level

Flanders represents the northern part of Belgium and is almost entirely situated within the Atlantic biogeographical region, with the exception of Voeren in the easternmost part, which belongs to the Continental biogeographical region. INBO is responsible for the assessment of the conservation status (CS) of habitat types in Flanders. The results for Flanders are integrated with the results of the Walloon and Brussels Capital region to assess the CS of habitat types on the scale of Belgium per biogeographical region. This integrated assessment is reported to the European Commission.

The methodology used by INBO to evaluate the CS of the criterion specific structure and functions (including typical species) is based on the general guidelines by @dgenvironment2017 and is described in more detail by @paelinckx2019. It requires information per habitat type on:

-   the fraction of the habitat area in good condition (as assessed following the criteria and indicators by @oosterlynvk2020) and its trend
-   the status of its habitat typical species (e.g. Red List status);
-   landscape ecological coherence of the habitat;
-   the existence of high pressures that cannot sufficiently be remediated by conservation measures.

MHQ supports the assessment of the habitat area that is in a good condition. We use the term 'biotic habitat quality' as the condition of a habitat is assessed based on biotic data. Further in this report we will only focus on this part of the information needs.

In Flanders 46 habitat types occur and several of these habitat types are subdivided into habitat subtypes (Appendix \@ref(annex1)). Nature policy in Flanders also requires information on the habitat quality for these habitat subtypes [@westra2011]. However, this information has a lower priority and therefore a lower precision (compared to the main habitat types) is acceptable. The report of @westra2011 also considered the need for assessing the habitat quality status within the network of Special Areas of Conservation (SAC) in Flanders with a higher precision. This is because most policy measures to improve the conservation status of habitat types are taken within SAC and we want to be able to evaluate these measures.         


# Overview of MHQ {#overview}

## Monitoring target 

Based on the information needs we can summarize the main targets of MHQ as follows:

+ the habitat quality status per habitat type and per habitat subtype for Flanders and for the network of SAC
  + What is the percentage of the habitat area that is in good/not-good condition^[We use the term 'not-good condition' as this is also used in the Article 17 reporting forms.]?
  + Is the percentage of habitat in not-good condition higher or lower than 25%?
  
+ the habitat quality short-term (12 years) and long-term (24 years) trend per habitat type and per habitat subtype for Flanders and for the network of SAC
  + What is the trend of the habitat area in good/not-good condition?
  + Is the habitat quality stable, improving or deteriorating?

The original design of MHQ [@westra2014] was mainly based on the target for the status of habitat quality. In this report we will evaluate how the design can be modified to better meet the monitoring target for the trend in habitat quality. We will evaluate different scenarios based on sample size calculations for status and trend in habitat quality. But first we summarize how habitat quality is defined and what needs to be measured in the field.


## Biotic habitat quality indicators

The report of @oosterlynck2020 provides a series of criteria and indicators aimed at determining the local conservation status (= habitat condition) for 46 habitat types and 42 habitat subtypes. Different types of indicators are included that are related to:

+ vegetation composition,
+ vegetation structure,
+ disturbances,
+ spatial connectivity.

For each indicator a threshold value defines whether the indicator is favourable or unfavourable. Combining the results for the different indicators allows an overall assessment of the habitat quality at a habitat location. The selection of the indicators and their threshold values is based on their capacity to cover the habitat's functioning in an objective (i.e. based on national and international scientific literature), unambiguous, practical, measurable and comprehensive way [@oosterlynck2020]. 

The R package LSVI [@lommelen2022] enables calculation and evaluation of the indicators for habitat quality in a standardized and semi-automated way and makes use of [@oosterlynck2020].


## Field measurements

The field measurements for MHQ consist of two parts:

+ vegetation composition: presence and cover of plant species per vegetation layer,
+ structure variables: measurement of variables related to vegetation structure.

The spatial scale at which these variables are measured, depends on the habitat type and is shown in \@ref(tab:tabscale). Note that these measurements do not allow the evaluation of the indicators related to spatial connectivity.  

```{r tabscale}
tabscale <- tibble(category = c("terrestrial", "terrestrial", "aquatic", "aquatic"),
                   "habitat type" = c("forest", "open", "stream", "standing water"),
                   "vegetation composition" = c("16 m x 16 m square plot", "3 m x 3 m square plot", "100 m river segment", "entire water body"),
                   "structure variables" = c("18 m diameter circle plot", "18 m diameter circle plot", "100 m river segment", "entire water body"))
tabscale %>%
  kable(caption= "Spatial scale at which the vegetation composition and structure variables are measured",
        booktabs = TRUE, 
        format = format_table) %>%
  kable_styling() %>%
  collapse_rows(1)
```


INBO developed standardized field protocols (sfp) for the MHQ field measurements that allow the evaluation of most of the indicators in [@oosterlynck2020]. The sfp for the aquatic habitat type 3260 has already been published [@leyssen_vegetatieopname_2017], while publication of the protocols for the terrestrial and standing water habitat types is planned in the near future. 












